name: Develop Workflow

on:
    push:
        branches:
            - develop
            - main
    
jobs:

    scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Run security scan
              run: echo "Running security scan"

    build:
        runs-on: ubuntu-latest
        environment: develop
        needs: [scan]

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: docker build
              run: |
                 docker build -t my-app:latest .
            
            - name: docker login
              run: |
                echo "${{ secrets.MY_APP_TOKEN }}" | docker login -u fmahmud26 --password-stdin

            - name: docker push
              run: |
                docker tag my-app:latest fmahmud26/my-app:latest
                docker push fmahmud26/my-app:latest



            
